---
sudo: false
branches:
  only:
  - master
jobs:
  include:
  - stage: build
    language: java
    jdk: openjdk11
    before_script: cd java
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE=java
  - language: java
    jdk: openjdk11
    before_script: cd algorithms/project-euler
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE="algorithms/project-euler"
  - language: rust
    before_script: cd rust/guessing_game
    cache: cargo
  - language: go
    go: "1.11"
    before_script: cd go
    go_import_path: github.com/matihost/learning/go
    script:
    - go build github.com/matihost/learning/go/cmd/http-server
    - go build github.com/matihost/learning/go/cmd/language