---
sudo: false
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
  - stage: build
    language: java
    jdk: openjdk11
    before_script: cd java
  - language: java
    jdk: openjdk11
    before_script: cd algorithms/project-euler
